<script setup lang="ts">
import { ArrowRight, Connection, DataBoard, Finished, Key, SetUp, TopRight } from '@element-plus/icons-vue'
import SiteHeader from '../components/SiteHeader.vue'
import SiteFooter from '../components/SiteFooter.vue'

const principles = [
  { icon: SetUp, title: '双引擎各司其职', desc: 'Java 管理企业边界，Python 执行 AI 工作负载。' },
  { icon: Finished, title: '安全进入主链路', desc: '高风险动作先审批再执行，不依赖事后补救。' },
  { icon: Key, title: '企业能力从第一天开始', desc: '多租户、RBAC、审计与预算不是后补模块。' },
  { icon: Connection, title: '工具成为组织资产', desc: '内部系统能力可授权、可治理、可重复使用。' },
]
const roadmap = [
  { year: '现在', title: '核心 Agent 工作流', desc: '创建、发布、对话、工具、知识库、用户与审计已经形成运行闭环。', status: '已可体验' },
  { year: '下一阶段', title: '协作与安全治理', desc: '多 Agent 编排、护栏试验台、用量分析和渠道中心进入产品界面。', status: '正在构建' },
  { year: '随后', title: '模板与插件生态', desc: '行业模板、第三方工具审核、开发者分发和版本管理。', status: '计划中' },
  { year: '长期', title: '组织智能运营', desc: '对话分析、质量评估、流程发现和持续优化建议。', status: '探索中' },
]
</script>

<template>
  <div class="public-page about-page"><SiteHeader /><main>
    <section class="about-hero"><div><span class="site-kicker">关于 AgentHub</span><h1>我们想做的不是<br>另一个聊天机器人。</h1><p>AgentHub 关注的是企业如何长期使用 Agent：既让业务团队快速尝试，又让技术与管理团队始终知道它能做什么、正在做什么、花了多少，以及什么时候必须由人决定。</p></div><blockquote><span>项目主张</span><p>“让业务创新的速度，和企业治理的边界，同时成立。”</p><small>AgentHub / 2026</small></blockquote></section>
    <section class="origin-story"><div class="origin-index">01</div><div><span class="site-kicker">为什么开始</span><h2>真正难的不是调用模型，而是让它进入组织。</h2></div><div class="origin-copy"><p>一个演示中的 Agent 可以自由访问工具、调用模型并给出答案；进入真实业务后，它需要身份、权限、审批、审计、预算和失败处理。</p><p>AgentHub 从一开始就把这些“看起来不智能”的能力放在系统中心。因为只有边界清楚，Agent 才能被团队放心使用。</p></div></section>
    <section class="principle-section"><div class="site-section-head"><div><span class="site-kicker">设计原则</span><h2>功能会增加，原则保持稳定。</h2></div><p>每条原则都对应一个明确的工程责任，不依赖营销概念。</p></div><div class="principle-grid"><article v-for="(item,index) in principles" :key="item.title"><span>0{{ index + 1 }}</span><el-icon><component :is="item.icon" /></el-icon><h3>{{ item.title }}</h3><p>{{ item.desc }}</p></article></div></section>
    <section class="system-section"><div class="system-copy"><span class="site-kicker">系统结构</span><h2>管理面与执行面，用实时通信协作。</h2><p>用户请求先经过 Java 管理面确认身份与策略，再进入 Python 运行时完成模型推理、知识检索和工具执行。</p><router-link to="/docs">阅读架构设计 <el-icon><ArrowRight /></el-icon></router-link></div><div class="system-stack"><article><span>体验层</span><strong>Vue 工作台</strong><p>官网、控制台、流程编排、对话与运营视图</p></article><article><span>管理面</span><strong>Spring Boot</strong><p>身份、权限、审批、审计、预算与多租户</p></article><i><b>gRPC</b></i><article><span>执行面</span><strong>Python Runtime</strong><p>模型路由、RAG、工具、护栏与会话状态</p></article><article><span>数据层</span><strong>PostgreSQL + Redis</strong><p>业务数据、向量、缓存、限流与实时状态</p></article></div></section>
    <section class="roadmap-section"><div class="roadmap-heading"><span class="site-kicker">开放路线图</span><h2>按能运行、能验证的阶段向前。</h2><p>我们不会一次性画完宏大的蓝图，而是让每一步都成为真实可用的产品能力。</p></div><div class="roadmap-list"><article v-for="item in roadmap" :key="item.year"><span>{{ item.year }}</span><div><h3>{{ item.title }}</h3><p>{{ item.desc }}</p></div><b>{{ item.status }}</b></article></div></section>
    <section class="open-source"><div><el-icon><DataBoard /></el-icon><span>开源项目 · MIT</span><h2>代码、文档和路线图都保持开放。</h2><p>欢迎提交 Issue、补充真实场景、开发工具连接器，或者直接参与代码贡献。</p></div><div class="repo-links"><a href="https://github.com/CoderDongHuang/agenthub" target="_blank" rel="noreferrer"><span>主要仓库</span><strong>GitHub</strong><small>源码 · Issue · Pull Request</small><el-icon><TopRight /></el-icon></a><a href="https://gitee.com/donghuang-C/agenthub" target="_blank" rel="noreferrer"><span>国内镜像</span><strong>Gitee</strong><small>同步代码与版本</small><el-icon><TopRight /></el-icon></a></div></section>
  </main><SiteFooter /></div>
</template>

<style scoped>
.about-hero { width: min(1240px, calc(100% - 64px)); min-height: 590px; margin: 0 auto; padding: 90px 0 72px; display: grid; grid-template-columns: 1.15fr .85fr; gap: 90px; align-items: center; }.about-hero h1 { margin-top: 20px; font-size: 60px; line-height: 1.07; }.about-hero > div > p { max-width: 720px; margin-top: 25px; color: var(--site-muted); font-size: 16px; line-height: 1.85; }.about-hero blockquote { min-height: 320px; padding: 32px; display: flex; flex-direction: column; border-radius: 8px; background: #e9f0f4; color: #3f5f73; transform: rotate(1.4deg); }.about-hero blockquote > span { font-size: 9px; font-weight: 700; }.about-hero blockquote p { margin-top: 70px; font-family: Georgia, "Songti SC", serif; font-size: 28px; line-height: 1.55; font-weight: 700; }.about-hero blockquote small { margin-top: auto; color: #708896; font-size: 9px; }
.origin-story { padding: 100px max(30px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: 80px .9fr 1.1fr; gap: 50px; background: var(--site-primary-dark); color: white; }.origin-index { color: #a9c1b2; font-size: 10px; }.origin-story .site-kicker { color: #bcd0c3; }.origin-story h2 { margin-top: 18px; font-size: 42px; line-height: 1.17; }.origin-copy p { color: #cbd8d0; font-size: 14px; line-height: 1.85; }.origin-copy p + p { margin-top: 22px; }
.principle-section { padding: 96px max(30px, calc((100vw - 1240px) / 2)); background: #f4f0e8; }.principle-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }.principle-grid article { min-height: 280px; padding: 22px; display: grid; grid-template-columns: 1fr auto; align-content: start; border: 1px solid #ddd7cc; border-radius: 8px; background: rgba(255,255,255,.7); }.principle-grid article > span { color: #969e99; font-size: 9px; }.principle-grid article .el-icon { color: var(--site-primary); font-size: 22px; }.principle-grid h3 { grid-column: 1 / -1; margin-top: 90px; font-size: 17px; }.principle-grid p { grid-column: 1 / -1; margin-top: 10px; color: var(--site-muted); font-size: 10px; line-height: 1.65; }
.system-section { padding: 100px max(30px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: .65fr 1.35fr; gap: 80px; align-items: center; background: white; }.system-copy h2 { margin-top: 18px; font-size: 40px; line-height: 1.17; }.system-copy p { margin-top: 16px; color: var(--site-muted); font-size: 13px; line-height: 1.75; }.system-copy a { margin-top: 25px; display: inline-flex; align-items: center; gap: 7px; color: var(--site-primary-dark); text-decoration: none; font-size: 11px; font-weight: 800; }.system-stack { position: relative; padding-left: 45px; }.system-stack::before { content: ''; position: absolute; left: 18px; top: 30px; bottom: 30px; width: 2px; background: var(--site-line-strong); }.system-stack article { position: relative; min-height: 105px; margin-top: 10px; padding: 18px 22px; display: grid; grid-template-columns: 110px 1fr; align-items: center; border: 1px solid var(--site-line); border-radius: 8px; background: #fafbf9; }.system-stack article::before { content: ''; position: absolute; left: -34px; top: 50%; width: 10px; height: 10px; border: 4px solid white; border-radius: 50%; background: var(--site-primary); transform: translateY(-50%); }.system-stack article span { color: var(--site-primary); font-size: 9px; font-weight: 700; }.system-stack article strong { font-size: 16px; }.system-stack article p { grid-column: 2; margin-top: 6px; color: var(--site-muted); font-size: 9px; }.system-stack > i { position: absolute; z-index: 2; left: 2px; top: 47%; width: 34px; height: 34px; display: grid; place-items: center; border-radius: 50%; background: var(--site-blue); color: white; font-size: 7px; font-style: normal; }
.roadmap-section { padding: 100px max(30px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: .65fr 1.35fr; gap: 80px; background: #e9f0f4; }.roadmap-heading h2 { margin-top: 18px; font-size: 40px; line-height: 1.17; }.roadmap-heading p { margin-top: 16px; color: #687b87; font-size: 13px; line-height: 1.75; }.roadmap-list { border-top: 1px solid #c8d6de; }.roadmap-list article { min-height: 125px; padding: 20px 0; display: grid; grid-template-columns: 90px 1fr auto; gap: 20px; align-items: center; border-bottom: 1px solid #c8d6de; }.roadmap-list article > span { color: var(--site-blue); font-size: 9px; font-weight: 700; }.roadmap-list h3 { font-size: 16px; }.roadmap-list p { margin-top: 7px; color: #687b87; font-size: 10px; line-height: 1.5; }.roadmap-list b { padding: 6px 9px; border-radius: 5px; background: rgba(255,255,255,.7); color: #5e7889; font-size: 8px; }
.open-source { padding: 96px max(30px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: .7fr 1.3fr; gap: 80px; background: #f2eee6; }.open-source > div:first-child > .el-icon { color: var(--site-coral); font-size: 28px; }.open-source > div:first-child > span { display: block; margin-top: 18px; color: var(--site-coral); font-size: 9px; font-weight: 700; }.open-source h2 { margin-top: 15px; font-size: 38px; line-height: 1.17; }.open-source p { margin-top: 15px; color: var(--site-muted); font-size: 12px; line-height: 1.7; }.repo-links { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }.repo-links a { min-height: 240px; padding: 24px; display: flex; flex-direction: column; position: relative; border: 1px solid #ddd6ca; border-radius: 8px; background: rgba(255,255,255,.7); color: var(--site-ink); text-decoration: none; }.repo-links a > span { color: var(--site-coral); font-size: 9px; font-weight: 700; }.repo-links a strong { margin-top: auto; font-size: 24px; }.repo-links a small { margin-top: 7px; color: var(--site-muted); font-size: 9px; }.repo-links a .el-icon { position: absolute; right: 22px; top: 22px; }
@media (max-width: 980px) { .about-hero, .origin-story, .system-section, .roadmap-section, .open-source { grid-template-columns: 1fr; }.origin-index { display: none; }.principle-grid { grid-template-columns: 1fr 1fr; } }
@media (max-width: 650px) { .about-hero { width: calc(100% - 32px); padding: 62px 0; }.about-hero h1 { font-size: 40px; }.origin-story, .principle-section, .system-section, .roadmap-section, .open-source { padding: 72px 16px; }.principle-grid, .repo-links { grid-template-columns: 1fr; }.principle-grid article { min-height: 220px; }.roadmap-list article { grid-template-columns: 70px 1fr; }.roadmap-list article > b { grid-column: 2; justify-self: start; } }
</style>
