<script setup lang="ts">
import { ArrowRight, Check, CircleCheck, Connection, DataAnalysis, Lock, Operation, Tools } from '@element-plus/icons-vue'
import SiteHeader from '../components/SiteHeader.vue'
import SiteFooter from '../components/SiteFooter.vue'

const trace = [
  { type: 'THOUGHT', text: '需要先核验退款规则与订单状态', tone: 'blue' },
  { type: 'ACTION', text: 'order.lookup({ id: "AH-814" })', tone: 'amber' },
  { type: 'OBSERVATION', text: '订单有效，退款金额 ¥8,600', tone: 'green' },
]
</script>

<template>
  <div class="public-page features-page">
    <SiteHeader />
    <main>
      <section class="feature-hero"><div><span class="site-kicker">CORE FEATURES</span><h1>核心差异，不用空洞的<br>“安全、高效、易用”表达。</h1><p>每一项能力都对应一个真实工程责任，并在界面上呈现它如何工作。</p></div><div class="hero-signal"><span><i /> CONTROL PLANE ONLINE</span><strong>4</strong><small>核心能力模块</small><div><b>JAVA</b><i>gRPC</i><b>PYTHON</b></div></div></section>

      <section class="bento-section">
        <div class="bento-heading"><span class="site-kicker">ENTERPRISE AGENT ARCHITECTURE</span><h2>为企业级合规而生的 Agent 引擎。</h2><p>双引擎、动态审批、Trace 与工具生态不是彼此孤立的功能，它们共同组成执行边界。</p></div>
        <div class="feature-bento">
          <article class="bento-card engine-card">
            <header><span class="feature-icon green"><el-icon><Operation /></el-icon></span><div><small>01 / DUAL ENGINE</small><h3>Java + Python 双引擎协同</h3></div><b><i /> CONNECTED</b></header>
            <p>Java 管理企业身份、RBAC、多租户、审批与审计；Python 运行时专注模型路由、RAG、工具与 Agent 执行。</p>
            <div class="engine-topology"><section><span>CONTROL PLANE</span><strong>Spring Boot</strong><p><i /> Security Gateway</p><p><i /> Approval & Audit</p></section><div><span>REST</span><i /><b>gRPC</b><i /><span>EVENTS</span></div><section><span>EXECUTION PLANE</span><strong>Python Runtime</strong><p><i /> Model Router</p><p><i /> Agent & Tools</p></section></div>
          </article>

          <article class="bento-card approval-card">
            <header><span class="feature-icon amber"><el-icon><Lock /></el-icon></span><div><small>02 / APPROVAL GATE</small><h3>动态审批卡点</h3></div></header>
            <p>敏感工具调用在真正执行前暂停，并把完整参数与风险原因交给负责人。</p>
            <div class="approval-widget"><span><i /> HIGH RISK</span><strong>refund.execute</strong><small>amount: ¥8,600</small><div><button>拒绝</button><button><el-icon><Check /></el-icon>批准并继续</button></div></div>
          </article>

          <article class="bento-card trace-card">
            <header><span class="feature-icon blue"><el-icon><Connection /></el-icon></span><div><small>03 / LIVE TRACE</small><h3>ReAct 思考链路</h3></div></header>
            <p>Thought、Action 与 Observation 沿同一条时间线实时展开。</p>
            <div class="trace-widget"><article v-for="item in trace" :key="item.type" :class="item.tone"><i /><span>{{ item.type }}</span><strong>{{ item.text }}</strong></article></div>
          </article>

          <article class="bento-card tool-card">
            <header><span class="feature-icon cyan"><el-icon><Tools /></el-icon></span><div><small>04 / HOT PLUG TOOLS</small><h3>Python 工具热同步</h3></div><b>4 ACTIVE</b></header>
            <p>把脚本放入自定义目录，运行时解析 JSON Schema 并同步到可授权、可审批的工具池。</p>
            <div class="tool-terminal"><header><span>custom/</span><b>WATCHING</b></header><code><span>+</span> refund_execute.py</code><code><span>+</span> contract_review.py</code><footer><i /> Schema synchronized in 118 ms</footer></div>
          </article>
        </div>
      </section>

      <section class="governance-strip"><div><span class="site-kicker">SHARED GOVERNANCE</span><h2>所有 Agent 共享一套企业边界。</h2></div><article><el-icon><Lock /></el-icon><strong>身份与权限</strong><small>谁能看、谁能改、谁能执行</small></article><article><el-icon><CircleCheck /></el-icon><strong>人工审批</strong><small>关键动作确认后继续</small></article><article><el-icon><DataAnalysis /></el-icon><strong>审计与成本</strong><small>执行、Token 与结果统一记录</small></article></section>

      <section class="feature-flow"><div><span class="site-kicker">ONE CONTROLLED PATH</span><h2>一次请求如何经过完整平台。</h2><p>每个节点有明确输入、责任与失败处理，运行过程随时可被人接管。</p></div><ol><li><b>01</b><span>身份与策略</span><strong>Java Gateway</strong></li><li><b>02</b><span>模型与知识</span><strong>Agent Runtime</strong></li><li><b>03</b><span>工具与审批</span><strong>Risk Gate</strong></li><li><b>04</b><span>结果与归档</span><strong>Trace Store</strong></li></ol></section>

      <section class="site-cta-band"><div><span class="site-kicker">SEE IT RUN</span><h2>进入本地工作台，检查真实请求的完整 Trace。</h2><p>控制台内部保持现有业务功能，本页只负责清楚展示平台能力。</p></div><router-link to="/login">进入 Agent 工作台 <el-icon><ArrowRight /></el-icon></router-link></section>
    </main>
    <SiteFooter />
  </div>
</template>

<style scoped>
.feature-hero { min-height: 510px; padding: 86px max(28px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: 1.15fr .85fr; gap: 80px; align-items: center; background: #090d10; }.feature-hero h1 { margin-top: 18px; color: #f1f5f3; font-size: 51px; line-height: 1.08; }.feature-hero > div:first-child > p { max-width: 680px; margin-top: 22px; color: var(--site-muted); font-size: 13px; line-height: 1.8; }.hero-signal { min-height: 250px; padding: 24px; display: flex; flex-direction: column; border: 1px solid #303940; border-radius: 8px; background: #101417; box-shadow: 14px 14px 0 #111a15; }.hero-signal > span { display: flex; align-items: center; gap: 7px; color: #67dda0; font: 7px ui-monospace, monospace; }.hero-signal > span i { width: 6px; height: 6px; border-radius: 50%; background: #5de09d; box-shadow: 0 0 9px rgba(93,224,157,.6); }.hero-signal > strong { margin-top: auto; color: #ecf2ee; font-size: 54px; }.hero-signal > small { color: #68737a; font-size: 8px; }.hero-signal > div { margin-top: 20px; display: grid; grid-template-columns: 1fr 70px 1fr; align-items: center; }.hero-signal > div b { min-height: 44px; display: grid; place-items: center; border: 1px solid #304139; border-radius: 5px; background: #151e19; color: #87d8ad; font: 8px ui-monospace, monospace; }.hero-signal > div i { color: #69747b; font: 7px ui-monospace, monospace; text-align: center; }
.bento-section { padding: 96px max(28px, calc((100vw - 1240px) / 2)); background: #0d1013; }.bento-heading { max-width: 760px; }.bento-heading h2 { margin-top: 17px; color: #edf3ef; font-size: 39px; }.bento-heading > p { margin-top: 13px; color: var(--site-muted); font-size: 11px; line-height: 1.7; }.feature-bento { margin-top: 40px; display: grid; grid-template-columns: 1.15fr .85fr; gap: 12px; }.bento-card { min-width: 0; min-height: 360px; padding: 22px; display: flex; flex-direction: column; border: 1px solid #2d353b; border-radius: 8px; background: #121619; overflow: hidden; }.bento-card:hover { border-color: #3e4c45; transform: translateY(-2px); }.bento-card > header { display: grid; grid-template-columns: 42px 1fr auto; gap: 11px; align-items: center; }.feature-icon { width: 40px; height: 40px; display: grid; place-items: center; border: 1px solid #315440; border-radius: 7px; background: #16261e; color: #6ee1a5; font-size: 18px; }.feature-icon.amber { border-color: #5a4723; background: #21190c; color: #e5b75d; }.feature-icon.blue { border-color: #2f4c5d; background: #12212a; color: #73bae5; }.feature-icon.cyan { border-color: #275153; background: #112324; color: #5dd4d7; }.bento-card header small { color: #5f6970; font: 7px ui-monospace, monospace; }.bento-card h3 { margin-top: 5px; color: #e0e8e3; font-size: 14px; }.bento-card header > b { color: #68daa0; font: 7px ui-monospace, monospace; }.bento-card header > b i { display: inline-block; width: 6px; height: 6px; margin-right: 5px; border-radius: 50%; background: #5adf9d; }.bento-card > p { max-width: 660px; margin-top: 18px; color: #7d888f; font-size: 10px; line-height: 1.7; }
.engine-topology { margin-top: auto; display: grid; grid-template-columns: 1fr 85px 1fr; align-items: center; }.engine-topology section { min-height: 145px; padding: 16px; display: flex; flex-direction: column; border: 1px solid #2d3d35; border-radius: 7px; background: #0f1512; }.engine-topology section > span { color: #577364; font: 7px ui-monospace, monospace; }.engine-topology section > strong { margin: 12px 0; color: #cbe1d4; font-size: 14px; }.engine-topology section p { margin-top: 8px; display: flex; align-items: center; gap: 6px; color: #708079; font-size: 8px; }.engine-topology section p i { width: 5px; height: 5px; border-radius: 50%; background: #5bdc9a; }.engine-topology > div { display: flex; flex-direction: column; align-items: center; color: #5e686f; font: 6px ui-monospace, monospace; }.engine-topology > div i { width: 100%; height: 1px; margin: 9px 0; background: #344039; }.engine-topology > div b { color: #79a98f; font-size: 7px; }
.approval-card { border-color: #433821; }.approval-widget { margin-top: auto; padding: 15px; display: flex; flex-direction: column; border: 1px solid #5a4723; border-radius: 7px; background: #20190c; }.approval-widget > span { display: flex; align-items: center; gap: 6px; color: #c29d50; font: 7px ui-monospace, monospace; }.approval-widget > span i { width: 6px; height: 6px; border-radius: 50%; background: #e6b85d; box-shadow: 0 0 9px rgba(230,184,93,.48); }.approval-widget > strong { margin-top: 13px; color: #e5d0a7; font-size: 13px; }.approval-widget > small { margin-top: 6px; color: #907d57; font-size: 8px; }.approval-widget > div { margin-top: 16px; display: grid; grid-template-columns: .8fr 1.2fr; gap: 7px; }.approval-widget button { min-height: 34px; display: flex; align-items: center; justify-content: center; gap: 5px; border: 1px solid #65512b; border-radius: 5px; background: transparent; color: #b79b64; font: inherit; font-size: 8px; }.approval-widget button:last-child { border-color: #d5a94e; background: #dfb252; color: #1b1306; font-weight: 800; }
.trace-widget { position: relative; margin-top: auto; padding-left: 14px; }.trace-widget::before { content: ''; position: absolute; top: 10px; bottom: 10px; left: 3px; width: 1px; background: #334149; }.trace-widget article { position: relative; min-height: 57px; display: flex; flex-direction: column; justify-content: center; border-bottom: 1px solid #252d32; }.trace-widget article > i { position: absolute; left: -14px; width: 7px; height: 7px; border: 2px solid #121619; border-radius: 50%; background: #6fb7e1; }.trace-widget article.amber > i { background: #e4b45a; }.trace-widget article.green > i { background: #57da98; }.trace-widget span { color: #5c6870; font: 6px ui-monospace, monospace; }.trace-widget strong { margin-top: 5px; overflow: hidden; color: #aeb9b2; font-size: 8px; text-overflow: ellipsis; white-space: nowrap; }
.tool-card { min-height: 330px; }.tool-terminal { margin-top: auto; border: 1px solid #2a373a; border-radius: 7px; background: #0c1012; overflow: hidden; }.tool-terminal > header { min-height: 36px; padding: 0 11px; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #293236; color: #657177; font: 7px ui-monospace, monospace; }.tool-terminal > header b { color: #56c8ca; }.tool-terminal code { min-height: 40px; padding: 0 12px; display: flex; align-items: center; gap: 8px; border-bottom: 1px solid #20272b; color: #8aa49a; font-size: 8px; }.tool-terminal code span { color: #61d9a0; }.tool-terminal footer { min-height: 37px; padding: 0 12px; display: flex; align-items: center; gap: 7px; color: #5cbba1; font-size: 7px; }.tool-terminal footer i { width: 6px; height: 6px; border-radius: 50%; background: #57d89b; }
.governance-strip { padding: 80px max(28px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: 1.3fr repeat(3,.7fr); border-top: 1px solid #263137; border-bottom: 1px solid #263137; background: #11191e; }.governance-strip > div { padding-right: 35px; }.governance-strip h2 { margin-top: 16px; color: #e9efeb; font-size: 32px; }.governance-strip article { min-height: 190px; padding: 20px; display: flex; flex-direction: column; border-left: 1px solid #2b383f; }.governance-strip article .el-icon { color: #70bce6; font-size: 21px; }.governance-strip article strong { margin-top: auto; color: #c9d4cd; font-size: 11px; }.governance-strip article small { margin-top: 7px; color: #71818a; font-size: 8px; line-height: 1.5; }
.feature-flow { padding: 90px max(28px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: .7fr 1.3fr; gap: 70px; background: #0d1013; }.feature-flow h2 { margin-top: 17px; color: #edf3ef; font-size: 35px; }.feature-flow > div p { margin-top: 14px; color: var(--site-muted); font-size: 10px; line-height: 1.7; }.feature-flow ol { display: grid; grid-template-columns: 1fr 1fr; gap: 9px; list-style: none; }.feature-flow li { min-height: 130px; padding: 17px; display: flex; flex-direction: column; border: 1px solid #2d353a; border-radius: 7px; background: #121619; }.feature-flow li b { color: #5ee0a0; font: 7px ui-monospace, monospace; }.feature-flow li span { margin-top: auto; color: #69747b; font-size: 8px; }.feature-flow li strong { margin-top: 6px; color: #cbd5ce; font-size: 12px; }
@media (max-width: 900px) { .feature-hero, .feature-flow { grid-template-columns: 1fr; }.feature-bento { grid-template-columns: 1fr; }.governance-strip { grid-template-columns: 1fr 1fr 1fr; }.governance-strip > div { grid-column: 1 / -1; margin-bottom: 25px; } }
@media (max-width: 700px) { .feature-hero, .bento-section, .governance-strip, .feature-flow { padding: 65px 16px; }.feature-hero h1 { font-size: 38px; }.bento-heading h2 { font-size: 31px; }.engine-topology { grid-template-columns: 1fr; gap: 8px; }.engine-topology > div { min-height: 35px; flex-direction: row; justify-content: center; gap: 7px; }.engine-topology > div i { width: 30px; margin: 0; }.governance-strip { grid-template-columns: 1fr; }.governance-strip > div { grid-column: 1; }.governance-strip article { min-height: 140px; border-left: 0; border-top: 1px solid #2b383f; }.feature-flow ol { grid-template-columns: 1fr; } }
</style>
