<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { Collection, Delete, Document, Plus, Refresh, Upload } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import api from '../api'

interface KnowledgeDoc { id:number; filename:string; file_type?:string; file_size?:number; status?:string; source_version?:number; created_at?:string }
const { locale } = useI18n()
const tx = (zh:string,en:string) => locale.value === 'en-US' ? en : zh
const kbId = 1
const activeView = ref('assets')
const docs = ref<KnowledgeDoc[]>([])
const stats = ref<any>({ total_chunks:0, documents:0 })
const operations = ref<any>({})
const sources = ref<any[]>([])
const versions = ref<any[]>([])
const evaluationRuns = ref<any[]>([])
const loading = ref(false)
const indexingId = ref<number|null>(null)
const uploadVisible = ref(false)
const textVisible = ref(false)
const uploadFile = ref<File|null>(null)
const textForm = ref({ title:'', content:'' })
const sourceForm = ref({ sourceKey:'manual-operations', sourceType:'manual' })
const syncForm = ref({ sourceId:0, cursor:'v1', documents:'[{"externalId":"policy-1","title":"Policy","content":"AgentHub knowledge operations"}]' })
const evaluationForm = ref({ query:'AgentHub knowledge operations', expectedDocumentId:undefined as number|undefined })
const indexedCount = computed(() => docs.value.filter(doc => ['indexed','ready'].includes(doc.status || '')).length)
const totalSize = computed(() => docs.value.reduce((sum,doc) => sum + Number(doc.file_size || 0),0))
const views = computed(() => [{id:'assets',label:tx('知识资产','Assets')},{id:'sources',label:tx('数据源同步','Source sync')},{id:'quality',label:tx('索引与质量','Index & quality')}])

function formatSize(size:number){ if(!size)return '0 KB'; return size>=1048576?`${(size/1048576).toFixed(1)} MB`:`${(size/1024).toFixed(1)} KB` }
function percent(value:number){ return `${(Number(value||0)*100).toFixed(1)}%` }
async function refreshAll(){
  loading.value=true
  const responses=await Promise.allSettled([api.get(`/knowledge/docs?kbId=${kbId}`),api.get('/knowledge/stats'),api.get(`/product/knowledge/${kbId}/operations`),api.get(`/product/knowledge/${kbId}/sources`),api.get(`/product/knowledge/${kbId}/index-versions`),api.get(`/product/knowledge/${kbId}/evaluation-runs`)])
  const data=responses.map(item=>item.status==='fulfilled'?(item.value as any).data:null)
  docs.value=data[0]||[];stats.value=data[1]?.stats||{total_chunks:0,documents:0};operations.value=data[2]||{};sources.value=data[3]||[];versions.value=data[4]||[];evaluationRuns.value=data[5]||[]
  if(!syncForm.value.sourceId&&sources.value.length)syncForm.value.sourceId=Number(sources.value[0].id)
  loading.value=false
}
async function upload(){
  if(!uploadFile.value)return
  if(uploadFile.value.size>25*1024*1024)return ElMessage.error(tx('文件不能超过 25 MB','File must not exceed 25 MB'))
  const data=new FormData();data.append('file',uploadFile.value);data.append('kbId',String(kbId))
  try{const response=await api.post('/knowledge/upload',data,{headers:{'Content-Type':'multipart/form-data'}}) as any;await indexDoc(Number(response.data.id));uploadVisible.value=false;uploadFile.value=null}catch(error:any){ElMessage.error(error?.response?.data?.message||tx('上传失败','Upload failed'))}
}
async function addText(){
  if(!textForm.value.title||!textForm.value.content)return ElMessage.warning(tx('请填写标题和内容','Enter title and content'))
  try{const response=await api.post('/knowledge/text',{...textForm.value,kbId:String(kbId)}) as any;await indexDoc(Number(response.data.id));textVisible.value=false;textForm.value={title:'',content:''}}catch(error:any){ElMessage.error(error?.response?.data?.message||tx('添加失败','Add failed'))}
}
async function indexDoc(id:number){ indexingId.value=id;try{const response=await api.post(`/knowledge/docs/${id}/index`) as any;if(response.data?.status!=='ok')throw new Error(response.data?.message);ElMessage.success(tx(`已建立 ${response.data.chunks} 个分块`,`${response.data.chunks} chunks indexed`));await refreshAll()}finally{indexingId.value=null} }
async function removeDoc(doc:KnowledgeDoc){try{await ElMessageBox.confirm(tx(`确定删除“${doc.filename}”吗？`,`Delete "${doc.filename}"?`),tx('删除知识资产','Delete asset'));await api.delete(`/knowledge/docs/${doc.id}`);await refreshAll()}catch(error){if(error!=='cancel')ElMessage.error(tx('删除失败','Delete failed'))}}
async function createSource(){try{const response=await api.post(`/product/knowledge/${kbId}/sources`,sourceForm.value) as any;syncForm.value.sourceId=Number(response.data.id);ElMessage.success(tx('数据源已创建','Source created'));await refreshAll()}catch(error:any){ElMessage.error(error?.response?.data?.message||tx('创建失败','Creation failed'))}}
async function syncSource(){
  try{const documents=JSON.parse(syncForm.value.documents);const response=await api.post(`/product/knowledge/sources/${syncForm.value.sourceId}/sync`,{cursor:syncForm.value.cursor,documents}) as any;ElMessage.success(tx(`同步完成：新增 ${response.data.created}，更新 ${response.data.updated}，未变 ${response.data.unchanged}`,`Sync complete: ${response.data.created} created, ${response.data.updated} updated, ${response.data.unchanged} unchanged`));await refreshAll()}catch(error:any){ElMessage.error(error?.message||tx('同步失败','Sync failed'))}
}
async function rebuild(){try{const response=await api.post(`/product/knowledge/${kbId}/rebuild`) as any;ElMessage.success(tx(`索引版本 v${response.data.versionNo}：${response.data.status}`,`Index v${response.data.versionNo}: ${response.data.status}`));await refreshAll()}catch(error:any){ElMessage.error(error?.response?.data?.message||tx('重建失败','Rebuild failed'))}}
async function evaluate(){try{await api.post(`/product/knowledge/${kbId}/evaluate`,evaluationForm.value);ElMessage.success(tx('召回评测已完成','Retrieval evaluation completed'));await refreshAll()}catch(error:any){ElMessage.error(error?.response?.data?.message||tx('评测失败','Evaluation failed'))}}
onMounted(refreshAll)
</script>

<template>
  <div class="console-page knowledge-page" v-loading="loading">
    <div class="console-page-head"><div class="console-page-head__copy"><span>KNOWLEDGE OPERATIONS</span><h1>{{ tx('知识运营中心','Knowledge Operations') }}</h1><p>{{ tx('管理知识资产、数据源增量同步、索引版本、引用覆盖和召回质量。','Manage assets, incremental sources, index versions, citation coverage, and retrieval quality.') }}</p></div><div class="console-page-actions"><button class="console-secondary" @click="refreshAll"><el-icon><Refresh /></el-icon>{{ tx('刷新','Refresh') }}</button><button class="console-primary" @click="uploadVisible=true"><el-icon><Upload /></el-icon>{{ tx('上传文档','Upload') }}</button></div></div>
    <section class="knowledge-summary"><div><span>{{ tx('文档','Documents') }}</span><strong>{{ docs.length }}</strong></div><div><span>{{ tx('已索引','Indexed') }}</span><strong>{{ indexedCount }}</strong></div><div><span>{{ tx('引用覆盖率','Citation coverage') }}</span><strong>{{ percent(operations.citationCoverage) }}</strong></div><div><span>{{ tx('评测通过率','Evaluation pass rate') }}</span><strong>{{ percent(operations.evaluationPassRate) }}</strong></div><div><span>{{ tx('最新版本','Latest version') }}</span><strong>v{{ operations.latestVersion?.versionNo || 0 }}</strong></div></section>
    <nav class="knowledge-tabs"><button v-for="view in views" :key="view.id" :class="{active:activeView===view.id}" @click="activeView=view.id">{{ view.label }}</button></nav>

    <section v-if="activeView==='assets'" class="knowledge-workspace"><header><div><h2>{{ tx('知识资产目录','Knowledge asset catalog') }}</h2><p>{{ tx(`原始文件共 ${formatSize(totalSize)}，运行时索引 ${stats.total_chunks||0} 个分块。`,`Source files total ${formatSize(totalSize)} with ${stats.total_chunks||0} runtime chunks.`) }}</p></div><button class="console-secondary" @click="textVisible=true"><el-icon><Plus /></el-icon>{{ tx('添加文本','Add text') }}</button></header><div v-if="docs.length" class="asset-list"><article v-for="doc in docs" :key="doc.id"><el-icon><Document /></el-icon><div><strong>{{ doc.filename }}</strong><small>{{ (doc.file_type||'text').toUpperCase() }} · {{ formatSize(doc.file_size||0) }} · v{{ doc.source_version||1 }}</small></div><span :class="doc.status">{{ doc.status }}</span><button class="console-secondary" :disabled="indexingId===doc.id" @click="indexDoc(doc.id)">{{ tx('建立索引','Index') }}</button><button class="icon-action" :aria-label="tx('删除','Delete')" @click="removeDoc(doc)"><el-icon><Delete /></el-icon></button></article></div><div v-else class="empty"><el-icon><Collection /></el-icon><strong>{{ tx('知识库为空','Knowledge base is empty') }}</strong><button class="console-primary" @click="uploadVisible=true">{{ tx('上传第一个文档','Upload first document') }}</button></div></section>

    <section v-else-if="activeView==='sources'" class="knowledge-workspace"><header><div><h2>{{ tx('数据源连接器与增量同步','Source connectors and incremental sync') }}</h2><p>{{ tx('支持 manual、HTTP、webhook、file 与 import；内容哈希区分新增、更新和未变化。','Supports manual, HTTP, webhook, file, and import with content-hash change detection.') }}</p></div></header><div class="source-forms"><form @submit.prevent="createSource"><h3>{{ tx('创建连接器','Create connector') }}</h3><el-input v-model="sourceForm.sourceKey" :placeholder="tx('数据源键','Source key')" /><el-select v-model="sourceForm.sourceType"><el-option v-for="type in ['manual','http','webhook','file','import']" :key="type" :value="type" :label="type" /></el-select><button class="console-primary">{{ tx('创建','Create') }}</button></form><form @submit.prevent="syncSource"><h3>{{ tx('推送增量批次','Push incremental batch') }}</h3><el-select v-model="syncForm.sourceId"><el-option v-for="source in sources" :key="source.id" :value="Number(source.id)" :label="source.source_key" /></el-select><el-input v-model="syncForm.cursor" placeholder="cursor" /><el-input v-model="syncForm.documents" type="textarea" :rows="5" /><button class="console-primary" :disabled="!syncForm.sourceId">{{ tx('同步','Sync') }}</button></form></div><el-table :data="sources"><el-table-column prop="source_key" :label="tx('数据源','Source')" /><el-table-column prop="source_type" :label="tx('类型','Type')" /><el-table-column prop="sync_cursor" label="Cursor" /><el-table-column prop="status" :label="tx('状态','Status')" /><el-table-column prop="last_sync_at" :label="tx('最近同步','Last sync')" /></el-table></section>

    <section v-else class="knowledge-workspace"><header><div><h2>{{ tx('索引版本与召回质量','Index versions and retrieval quality') }}</h2><p>{{ tx('一键重建实际调用 Python RAG 索引，评测结果保留命中文档、分数和引用。','One-click rebuild invokes the Python RAG index; evaluations retain matches, scores, and citations.') }}</p></div><button class="console-primary" @click="rebuild"><el-icon><Refresh /></el-icon>{{ tx('一键重建','Rebuild index') }}</button></header><form class="evaluation-form" @submit.prevent="evaluate"><el-input v-model="evaluationForm.query" :placeholder="tx('评测查询','Evaluation query')" /><el-select v-model="evaluationForm.expectedDocumentId" clearable :placeholder="tx('期望文档（可选）','Expected document (optional)')"><el-option v-for="doc in docs" :key="doc.id" :value="doc.id" :label="doc.filename" /></el-select><button class="console-secondary">{{ tx('执行评测','Run evaluation') }}</button></form><h3 class="table-title">{{ tx('索引版本','Index versions') }}</h3><el-table :data="versions"><el-table-column prop="versionNo" :label="tx('版本','Version')" /><el-table-column prop="triggerType" :label="tx('触发方式','Trigger')" /><el-table-column prop="status" :label="tx('状态','Status')" /><el-table-column prop="documentCount" :label="tx('文档','Documents')" /><el-table-column prop="chunkCount" :label="tx('分块','Chunks')" /><el-table-column prop="completedAt" :label="tx('完成时间','Completed')" /></el-table><h3 class="table-title">{{ tx('召回评测记录','Retrieval evaluation runs') }}</h3><el-table :data="evaluationRuns"><el-table-column prop="query" :label="tx('查询','Query')" /><el-table-column prop="matched_document_id" :label="tx('命中文档','Matched document')" /><el-table-column prop="score" :label="tx('分数','Score')" /><el-table-column prop="passed" :label="tx('通过','Passed')" /><el-table-column prop="created_at" :label="tx('时间','Time')" /></el-table></section>

    <el-dialog v-model="uploadVisible" :title="tx('上传知识文档','Upload knowledge document')" width="460px"><label class="upload-drop"><el-icon><Upload /></el-icon><strong>{{ uploadFile?.name||tx('选择本地文档','Choose a local document') }}</strong><span>{{ tx('支持常用办公与文本格式，最大 25 MB','Common office and text formats, up to 25 MB') }}</span><input type="file" @change="(event:any)=>uploadFile=event.target?.files?.[0]||null" /></label><template #footer><el-button @click="uploadVisible=false">{{ tx('取消','Cancel') }}</el-button><el-button type="primary" :disabled="!uploadFile" @click="upload">{{ tx('上传','Upload') }}</el-button></template></el-dialog>
    <el-dialog v-model="textVisible" :title="tx('添加文本知识','Add text knowledge')" width="560px"><el-form label-position="top"><el-form-item :label="tx('标题','Title')"><el-input v-model="textForm.title" /></el-form-item><el-form-item :label="tx('内容','Content')"><el-input v-model="textForm.content" type="textarea" :rows="10" /></el-form-item></el-form><template #footer><el-button @click="textVisible=false">{{ tx('取消','Cancel') }}</el-button><el-button type="primary" @click="addText">{{ tx('添加','Add') }}</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.knowledge-summary{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--console-line);border-radius:8px;background:var(--console-panel);overflow:hidden}.knowledge-summary div{min-height:82px;padding:14px;display:flex;flex-direction:column;justify-content:space-between;border-right:1px solid var(--console-line)}.knowledge-summary div:last-child{border:0}.knowledge-summary span{color:var(--console-muted);font-size:9px}.knowledge-summary strong{font:20px ui-monospace,monospace}.knowledge-tabs{margin:14px 0;padding:4px;display:grid;grid-template-columns:repeat(3,1fr);gap:3px;border:1px solid var(--console-line);border-radius:8px;background:var(--console-panel-soft)}.knowledge-tabs button{min-height:40px;border:0;border-radius:5px;background:transparent;color:var(--console-muted);font:inherit;cursor:pointer}.knowledge-tabs button.active{background:var(--console-panel);color:var(--console-ink);box-shadow:inset 0 0 0 1px var(--console-accent)}.knowledge-workspace{border:1px solid var(--console-line);border-radius:8px;background:var(--console-panel);overflow:hidden}.knowledge-workspace>header{min-height:72px;padding:14px 16px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--console-line)}h2,h3{margin:0}.knowledge-workspace h2{font-size:14px}.knowledge-workspace header p{margin:5px 0 0;color:var(--console-muted);font-size:8px}.asset-list article{min-height:70px;padding:10px 16px;display:grid;grid-template-columns:30px 1fr 90px auto 34px;gap:10px;align-items:center;border-bottom:1px solid var(--console-line)}.asset-list article>div{display:flex;flex-direction:column;gap:5px}.asset-list small{color:var(--console-muted);font-size:8px}.asset-list span{font:8px ui-monospace,monospace;text-transform:uppercase}.icon-action{width:32px;height:32px;border:1px solid var(--console-line);background:transparent;color:var(--console-ink);cursor:pointer}.empty{min-height:330px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px}.empty>.el-icon{font-size:32px}.source-forms{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid var(--console-line)}.source-forms form{padding:16px;display:flex;flex-direction:column;gap:10px;border-right:1px solid var(--console-line)}.source-forms form:last-child{border:0}.source-forms h3,.table-title{font-size:11px}.evaluation-form{padding:14px;display:grid;grid-template-columns:2fr 1fr auto;gap:8px;border-bottom:1px solid var(--console-line)}.table-title{padding:14px 16px;border-top:1px solid var(--console-line)}.upload-drop{min-height:190px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;border:1px dashed var(--console-line-strong);background:var(--console-panel-soft);cursor:pointer}.upload-drop input{display:none}.upload-drop span{color:var(--console-muted);font-size:9px}
@media(max-width:900px){.knowledge-summary{grid-template-columns:repeat(3,1fr)}.source-forms{grid-template-columns:1fr}.source-forms form{border-right:0;border-bottom:1px solid var(--console-line)}}@media(max-width:640px){.knowledge-summary{grid-template-columns:repeat(2,1fr)}.knowledge-tabs,.evaluation-form{grid-template-columns:1fr}.asset-list article{grid-template-columns:30px 1fr auto}.asset-list article>span{grid-column:2}.asset-list article>.console-secondary,.asset-list article>.icon-action{grid-row:1/3}.asset-list article>.console-secondary{grid-column:3}.asset-list article>.icon-action{grid-column:4}}
</style>
