<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowRight, Check, Connection, Document, Lock, Monitor, OfficeBuilding, Service, Tools } from '@element-plus/icons-vue'
import SiteHeader from '../components/SiteHeader.vue'
import SiteFooter from '../components/SiteFooter.vue'

const scenarios = [
  { id: 'risk', no: '01', icon: OfficeBuilding, label: '金融风控审批', title: '高风险动作，必须在执行前被看见。', prompt: '核验理赔材料，并在证据充分时发起 ¥8,600 赔付。', model: 'DeepSeek V3', latency: '1.8 s', tools: ['policy.search', 'claim.verify', 'refund.execute'], approval: '赔付金额 > ¥5,000，财务负责人审批', result: '完成材料核验，退款工具在执行前暂停并生成审批单。', nodes: ['材料解析', '条款检索', '风险判断', '人工审批', '执行赔付'], tone: 'amber' },
  { id: 'service', no: '02', icon: Service, label: '智能合规客服', title: '回答要快，越界时也要及时交给人。', prompt: '客户询问保单等待期，并要求修改投保人联系方式。', model: 'Qwen Plus', latency: '720 ms', tools: ['knowledge.query', 'customer.lookup'], approval: '涉及身份信息修改，转人工坐席核验', result: '知识问答自动完成；账户变更请求连同上下文转交人工。', nodes: ['意图识别', '知识检索', '答案护栏', '人工接管', '会话归档'], tone: 'green' },
  { id: 'ops', no: '03', icon: Tools, label: '自动化运维助手', title: '先理解告警，再决定能否执行修复。', prompt: '分析支付服务错误率上升原因，并给出恢复操作。', model: 'Claude Sonnet', latency: '2.6 s', tools: ['metrics.query', 'runbook.search', 'shell.execute'], approval: '生产命令 shell.execute 需要双人审批', result: '定位数据库连接池耗尽，输出建议并阻断生产重启命令。', nodes: ['告警聚合', '历史对比', '运行手册', '变更审批', '结果通知'], tone: 'blue' },
  { id: 'rag', no: '04', icon: Document, label: '内部知识库 RAG', title: '引用组织知识，并保留答案依据。', prompt: '根据员工手册说明远程办公申请流程和审批人。', model: 'GPT-4o mini', latency: '540 ms', tools: ['rag.retrieve'], approval: '无高风险工具，自动执行', result: '命中 3 个知识切片，答案附带文档来源和章节位置。', nodes: ['查询改写', '向量检索', '切片重排', '答案生成', '引用归档'], tone: 'cyan' },
]
const activeId = ref('risk')
const active = computed(() => scenarios.find(item => item.id === activeId.value) || scenarios[0])
</script>

<template>
  <div class="public-page scenarios-page">
    <SiteHeader />
    <main>
      <section class="scenario-hero"><div><span class="site-kicker">USE CASE LAB</span><h1>项目使用场景，<br>用真实执行链路说明。</h1></div><p>选择场景即可查看 Prompt、模型、工具、审批条件和最终结果。这里展示的是 Agent 如何进入业务，而不是一组抽象行业标签。</p></section>

      <section class="scenario-switcher">
        <nav aria-label="场景选择">
          <span>SCENARIO INDEX</span>
          <button v-for="item in scenarios" :key="item.id" :class="{ active: activeId === item.id }" @click="activeId = item.id"><b>{{ item.no }}</b><el-icon><component :is="item.icon" /></el-icon><p><strong>{{ item.label }}</strong><small>{{ item.model }}</small></p><i /></button>
        </nav>
        <div :class="['scenario-workbench', active.tone]">
          <header><div><span>LIVE WORKFLOW SNAPSHOT</span><h2>{{ active.title }}</h2></div><b><i /> READY</b></header>
          <div class="scenario-meta"><article><span>PROMPT</span><p>“{{ active.prompt }}”</p></article><article><span>MODEL</span><strong>{{ active.model }}</strong><small>{{ active.latency }} estimated</small></article></div>
          <div class="workflow-track"><article v-for="(node, index) in active.nodes" :key="node" :class="{ approval: node.includes('审批') || node.includes('接管') }"><span>0{{ index + 1 }}</span><i /><strong>{{ node }}</strong><el-icon v-if="index < active.nodes.length - 1"><ArrowRight /></el-icon></article></div>
          <div class="execution-details"><section><span>TOOLS</span><div><code v-for="tool in active.tools" :key="tool">{{ tool }}</code></div></section><section class="approval-policy"><span>APPROVAL POLICY</span><p><el-icon><Lock /></el-icon>{{ active.approval }}</p></section></div>
          <div class="scenario-result"><el-icon><Check /></el-icon><p><span>EXPECTED RESULT</span><strong>{{ active.result }}</strong></p><b>TRACE ENABLED</b></div>
        </div>
      </section>

      <section class="scenario-principles"><div><span class="site-kicker">WORKFLOW RULES</span><h2>先定义交接与边界，再考虑自动化率。</h2></div><article><el-icon><Monitor /></el-icon><span>01</span><h3>真实输入与输出</h3><p>每个场景都从可复现的业务 Prompt 开始，以可验证结果结束。</p></article><article><el-icon><Lock /></el-icon><span>02</span><h3>明确审批条件</h3><p>模型可以判断和建议，但敏感工具必须由有权限的人放行。</p></article><article><el-icon><Connection /></el-icon><span>03</span><h3>完整 Trace</h3><p>模型选择、知识命中、工具参数和审批决定统一留痕。</p></article></section>

      <section class="scenario-templates"><div><span class="site-kicker">START FROM A TEMPLATE</span><h2>把熟悉的一项工作，变成第一条受控流程。</h2><p>场景模板会带上角色、模型建议、工具清单、护栏与审批规则。</p></div><div><article><span>SALES</span><strong>线索研究与跟进建议</strong><small>研究 Agent → CRM 工具 → 销售确认</small></article><article><span>LEGAL</span><strong>合同审阅与条款比对</strong><small>条款识别 → 风险分级 → 法务复核</small></article><article><span>ANALYTICS</span><strong>经营问答与周报生成</strong><small>指标检索 → 口径核验 → 报告归档</small></article></div></section>

      <section class="site-cta-band"><div><span class="site-kicker">选择一个起点</span><h2>在本地工作台验证第一条完整业务链路。</h2><p>从模拟请求开始，观察模型、工具、审批与审计是否符合预期。</p></div><router-link to="/login">进入 Agent 工作台 <el-icon><ArrowRight /></el-icon></router-link></section>
    </main>
    <SiteFooter />
  </div>
</template>

<style scoped>
.scenario-hero { width: min(1240px, calc(100% - 56px)); margin: 0 auto; padding: 84px 0 52px; display: grid; grid-template-columns: 1.15fr .85fr; gap: 70px; align-items: end; }.scenario-hero h1 { margin-top: 18px; color: #f0f5f2; font-size: 52px; line-height: 1.08; }.scenario-hero > p { color: var(--site-muted); font-size: 13px; line-height: 1.8; }
.scenario-switcher { width: min(1240px, calc(100% - 56px)); min-height: 650px; margin: 0 auto 90px; display: grid; grid-template-columns: 240px 1fr; border: 1px solid #30383e; border-radius: 8px; background: #0e1214; box-shadow: 0 24px 65px rgba(0,0,0,.36); overflow: hidden; }.scenario-switcher > nav { padding: 14px 10px; border-right: 1px solid #293137; background: #0b0f11; }.scenario-switcher > nav > span { padding: 0 10px 10px; display: block; color: #566168; font: 7px ui-monospace, monospace; }.scenario-switcher nav button { position: relative; width: 100%; min-height: 86px; padding: 11px 10px; display: grid; grid-template-columns: 25px 28px 1fr 5px; gap: 8px; align-items: center; border: 0; border-radius: 6px; background: transparent; color: #879198; font: inherit; text-align: left; cursor: pointer; }.scenario-switcher nav button:hover { background: #14191c; }.scenario-switcher nav button.active { background: #17221c; color: #dce5df; }.scenario-switcher nav button > b { color: #566168; font: 7px ui-monospace, monospace; }.scenario-switcher nav button > .el-icon { color: #78838a; font-size: 16px; }.scenario-switcher nav button.active > .el-icon { color: #68dfa2; }.scenario-switcher nav button p { display: flex; flex-direction: column; gap: 5px; }.scenario-switcher nav button strong { font-size: 9px; }.scenario-switcher nav button small { color: #5e686f; font-size: 7px; }.scenario-switcher nav button > i { width: 5px; height: 5px; border-radius: 50%; background: #3c454b; }.scenario-switcher nav button.active > i { background: #5de29f; box-shadow: 0 0 9px rgba(93,226,159,.5); }
.scenario-workbench { min-width: 0; padding: 28px; background: #101417; }.scenario-workbench > header { display: flex; align-items: flex-start; justify-content: space-between; }.scenario-workbench header span, .scenario-meta span, .execution-details section > span, .scenario-result span { color: #5f6a71; font: 7px ui-monospace, monospace; }.scenario-workbench h2 { max-width: 650px; margin-top: 8px; color: #edf3ef; font-size: 25px; line-height: 1.24; }.scenario-workbench > header > b { display: flex; align-items: center; gap: 6px; color: #6bdd9f; font: 7px ui-monospace, monospace; }.scenario-workbench > header > b i { width: 6px; height: 6px; border-radius: 50%; background: #5ce09e; box-shadow: 0 0 8px rgba(92,224,158,.6); }.scenario-meta { margin-top: 26px; display: grid; grid-template-columns: 1.45fr .55fr; border: 1px solid #2a3237; border-radius: 7px; overflow: hidden; }.scenario-meta article { min-height: 100px; padding: 16px; display: flex; flex-direction: column; justify-content: center; background: #0d1113; }.scenario-meta article + article { border-left: 1px solid #2a3237; }.scenario-meta p { margin-top: 10px; color: #aeb9b2; font-size: 10px; line-height: 1.6; }.scenario-meta strong { margin-top: 10px; color: #d9e3dd; font-size: 13px; }.scenario-meta small { margin-top: 5px; color: #667078; font-size: 7px; }
.workflow-track { min-height: 150px; margin-top: 16px; display: grid; grid-template-columns: repeat(5, 1fr); align-items: center; }.workflow-track article { position: relative; min-width: 0; min-height: 100px; padding: 12px; display: flex; flex-direction: column; border: 1px solid #2e383d; border-radius: 6px; background: #14191c; }.workflow-track article.approval { border-color: #5e4923; background: #20190c; }.workflow-track article > span { color: #59646b; font: 7px ui-monospace, monospace; }.workflow-track article > i { width: 7px; height: 7px; margin-top: 13px; border-radius: 50%; background: #5ee0a0; box-shadow: 0 0 8px rgba(94,224,160,.35); }.workflow-track article.approval > i { background: #e5b75d; box-shadow: 0 0 9px rgba(229,183,93,.42); }.workflow-track strong { margin-top: auto; overflow: hidden; color: #bec8c1; font-size: 8px; text-overflow: ellipsis; white-space: nowrap; }.workflow-track article > .el-icon { position: absolute; z-index: 2; right: -12px; top: 39px; width: 22px; height: 22px; display: grid; place-items: center; border: 1px solid #384147; border-radius: 50%; background: #0d1113; color: #68737a; }
.execution-details { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }.execution-details section { min-height: 94px; padding: 14px; border: 1px solid #2a3237; border-radius: 6px; background: #0d1113; }.execution-details section > div { margin-top: 11px; display: flex; flex-wrap: wrap; gap: 6px; }.execution-details code { padding: 6px 8px; border: 1px solid #313b40; border-radius: 4px; background: #141a1d; color: #88bca2; font-size: 7px; }.approval-policy p { margin-top: 11px; display: flex; align-items: center; gap: 7px; color: #d0ae68; font-size: 8px; line-height: 1.5; }.scenario-result { min-height: 68px; margin-top: 10px; padding: 12px; display: grid; grid-template-columns: 28px 1fr auto; gap: 9px; align-items: center; border: 1px solid #2f503d; border-radius: 6px; background: #132019; color: #67dda0; }.scenario-result p { display: flex; flex-direction: column; gap: 5px; }.scenario-result strong { color: #a9c9b7; font-size: 8px; line-height: 1.45; }.scenario-result > b { color: #5b9475; font: 6px ui-monospace, monospace; }
.scenario-principles { padding: 90px max(28px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: 1.25fr repeat(3, .75fr); border-top: 1px solid #243139; border-bottom: 1px solid #243139; background: #111920; }.scenario-principles > div { padding-right: 42px; }.scenario-principles h2, .scenario-templates h2 { margin-top: 17px; color: #edf3ef; font-size: 35px; line-height: 1.18; }.scenario-principles article { min-height: 245px; padding: 22px; display: flex; flex-direction: column; border-left: 1px solid #293942; }.scenario-principles article > .el-icon { color: #74bce8; font-size: 21px; }.scenario-principles article > span { margin-top: 27px; color: #607582; font: 7px ui-monospace, monospace; }.scenario-principles h3 { margin-top: auto; color: #d4dfd8; font-size: 13px; }.scenario-principles article p { margin-top: 8px; color: #758791; font-size: 9px; line-height: 1.6; }
.scenario-templates { padding: 90px max(28px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: .7fr 1.3fr; gap: 70px; background: #0d1013; }.scenario-templates > div:first-child > p { margin-top: 15px; color: var(--site-muted); font-size: 11px; line-height: 1.7; }.scenario-templates > div:last-child { border-top: 1px solid #2b3338; }.scenario-templates article { min-height: 105px; padding: 17px 0; display: grid; grid-template-columns: 80px 1fr; align-content: center; border-bottom: 1px solid #2b3338; }.scenario-templates article > span { color: #64dda0; font: 7px ui-monospace, monospace; }.scenario-templates article strong { color: #d5ded8; font-size: 12px; }.scenario-templates article small { grid-column: 2; margin-top: 6px; color: #6e7980; font-size: 8px; }
@media (max-width: 980px) { .scenario-hero, .scenario-templates { grid-template-columns: 1fr; gap: 28px; }.scenario-switcher { grid-template-columns: 190px 1fr; }.workflow-track { overflow-x: auto; grid-template-columns: repeat(5, 150px); }.scenario-principles { grid-template-columns: 1fr 1fr 1fr; }.scenario-principles > div { grid-column: 1 / -1; margin-bottom: 25px; } }
@media (max-width: 700px) { .scenario-hero { width: calc(100% - 32px); padding: 58px 0 38px; }.scenario-hero h1 { font-size: 37px; }.scenario-switcher { width: calc(100% - 32px); grid-template-columns: 1fr; }.scenario-switcher > nav { display: grid; grid-template-columns: 1fr 1fr; border-right: 0; border-bottom: 1px solid #293137; }.scenario-switcher > nav > span { grid-column: 1 / -1; }.scenario-switcher nav button { min-height: 70px; grid-template-columns: 20px 1fr 5px; }.scenario-switcher nav button > .el-icon { display: none; }.scenario-workbench { padding: 20px 12px; }.scenario-workbench h2 { font-size: 21px; }.scenario-meta, .execution-details { grid-template-columns: 1fr; }.scenario-meta article + article { border-left: 0; border-top: 1px solid #2a3237; }.scenario-result { grid-template-columns: 26px 1fr; }.scenario-result > b { display: none; }.scenario-principles, .scenario-templates { padding: 68px 16px; }.scenario-principles { grid-template-columns: 1fr; }.scenario-principles > div { grid-column: 1; }.scenario-principles article { min-height: 180px; border-left: 0; border-top: 1px solid #293942; } }
</style>
