<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowRight, Check, Clock, OfficeBuilding, Service, Tools, User } from '@element-plus/icons-vue'
import SiteHeader from '../components/SiteHeader.vue'
import SiteFooter from '../components/SiteFooter.vue'

const scenarios = [
  { id: 'claim', index: '01', icon: OfficeBuilding, label: '保险理赔', title: '材料很多，关键动作更要稳。', desc: 'Agent 读取事故材料、核对保单条款并整理赔付依据；真正执行赔付前，自动把金额、证据和风险交给负责人确认。', accent: 'sage', metrics: [['2 分钟', '首次响应'], ['60%', '处理提速'], ['100%', '关键动作留痕']], roles: ['材料识别 Agent', '条款分析 Agent', '赔付审批人', '客户沟通 Agent'] },
  { id: 'service', index: '02', icon: Service, label: '客户服务', title: '回答得快，也要知道何时交给人。', desc: '从知识库找到答案，判断用户情绪与问题难度。无法确认或用户不满意时，连同完整上下文一起转给人工坐席。', accent: 'blue', metrics: [['24/7', '持续服务'], ['42%', '人工减负'], ['1.2s', '平均响应']], roles: ['意图识别 Agent', '知识问答 Agent', '情绪判断', '人工坐席'] },
  { id: 'hr', index: '03', icon: User, label: '人力资源', title: '重复流程自动走，敏感决定由人做。', desc: '入职问答、材料收集和培训提醒由 Agent 完成；涉及薪酬、绩效和岗位调整时，严格遵守部门权限与审批流程。', accent: 'coral', metrics: [['3 天', '入职提速'], ['86%', '问题自助'], ['0', '跨部门泄露']], roles: ['入职助手', '制度检索 Agent', 'HR 审批人', '通知助手'] },
  { id: 'ops', index: '04', icon: Tools, label: 'IT 运维', title: '先理解告警，再执行修复。', desc: '聚合监控事件、检索历史故障和运行手册，自动形成修复建议。高风险命令经过审批后才能进入生产环境。', accent: 'amber', metrics: [['38%', 'MTTR 降低'], ['7×24', '告警归并'], ['双人', '高危审批']], roles: ['告警归并', '诊断 Agent', '变更审批人', '执行工具'] },
]
const activeId = ref('claim')
const active = computed(() => scenarios.find(item => item.id === activeId.value) || scenarios[0])
</script>

<template>
  <div class="public-page scenarios-page"><SiteHeader /><main>
    <section class="scenario-intro"><div><span class="site-kicker">真实工作场景</span><h1>把复杂工作拆清楚，<br>再交给 Agent。</h1></div><p>一个好场景不是“接入大模型”，而是明确谁负责理解、谁调用工具、哪里必须停下来等人确认，以及最后如何记录。</p></section>
    <section class="scenario-stage">
      <nav><button v-for="scenario in scenarios" :key="scenario.id" :class="{ active: activeId === scenario.id }" @click="activeId = scenario.id"><span>{{ scenario.index }}</span><el-icon><component :is="scenario.icon" /></el-icon><strong>{{ scenario.label }}</strong><small>查看流程</small></button></nav>
      <div :class="['scenario-story', active.accent]"><div class="story-copy"><span>{{ active.label }}</span><h2>{{ active.title }}</h2><p>{{ active.desc }}</p><router-link to="/login">使用这个场景模板 <el-icon><ArrowRight /></el-icon></router-link></div><div class="story-metrics"><div v-for="metric in active.metrics" :key="metric[1]"><strong>{{ metric[0] }}</strong><span>{{ metric[1] }}</span></div></div><div class="story-roles"><span>协作角色</span><ol><li v-for="(role, index) in active.roles" :key="role"><b>0{{ index + 1 }}</b><i /><strong>{{ role }}</strong><el-icon v-if="index < active.roles.length - 1"><ArrowRight /></el-icon></li></ol></div></div>
    </section>
    <section class="scene-principles"><div class="principle-intro"><span class="site-kicker">设计一个好流程</span><h2>先定义交接，再考虑自动化。</h2></div><article><el-icon><Clock /></el-icon><h3>明确响应时限</h3><p>每个节点都知道等待多久、失败后交给谁。</p></article><article><el-icon><Check /></el-icon><h3>划清决策边界</h3><p>模型可以建议，但敏感决定必须由有权限的人确认。</p></article><article><el-icon><Tools /></el-icon><h3>限制工具能力</h3><p>只给 Agent 完成当前任务所需的最小工具集合。</p></article></section>
    <section class="template-wall"><div class="template-title"><span class="site-kicker">更多可扩展方向</span><h2>从一个模板开始，再适配自己的组织。</h2><p>场景模板会包含角色、模型建议、工具清单、护栏和审批规则。</p></div><div class="template-list"><article><span>销售</span><h3>线索研究与跟进建议</h3><p>聚合客户信息、生成拜访准备，并把跟进动作写入 CRM。</p></article><article><span>法务</span><h3>合同审阅与条款比对</h3><p>识别风险条款、比对标准模板，并生成可解释的修改建议。</p></article><article><span>经营</span><h3>数据问答与周报生成</h3><p>连接指标平台，回答经营问题并按固定口径形成周报。</p></article></div></section>
    <section class="site-cta-band"><div><span class="site-kicker">选择一个起点</span><h2>把你最熟悉的一项工作，搭成第一条流程。</h2><p>先用模拟运行验证角色、工具和审批点，再发布到真实渠道。</p></div><router-link to="/login">打开流程编排 <el-icon><ArrowRight /></el-icon></router-link></section>
  </main><SiteFooter /></div>
</template>

<style scoped>
.scenario-intro { width: min(1240px, calc(100% - 64px)); margin: 0 auto; padding: 88px 0 60px; display: grid; grid-template-columns: 1.15fr .85fr; gap: 70px; align-items: end; }.scenario-intro h1 { margin-top: 20px; font-size: 58px; line-height: 1.08; }.scenario-intro > p { color: var(--site-muted); font-size: 16px; line-height: 1.8; }
.scenario-stage { width: min(1240px, calc(100% - 64px)); min-height: 620px; margin: 0 auto 92px; display: grid; grid-template-columns: 230px 1fr; border: 1px solid var(--site-line); border-radius: 8px; background: white; overflow: hidden; box-shadow: var(--site-shadow); }.scenario-stage nav { padding: 12px; border-right: 1px solid var(--site-line); background: #f3f6f3; }.scenario-stage nav button { width: 100%; min-height: 112px; padding: 16px; display: grid; grid-template-columns: 28px 28px 1fr; grid-template-rows: 1fr 1fr; gap: 4px 8px; align-items: center; border: 0; border-radius: 7px; background: transparent; color: var(--site-muted); font: inherit; text-align: left; cursor: pointer; }.scenario-stage nav button + button { margin-top: 4px; }.scenario-stage nav button > span { grid-row: 1 / 3; font-size: 10px; }.scenario-stage nav button .el-icon { grid-row: 1 / 3; font-size: 19px; }.scenario-stage nav button strong { align-self: end; font-size: 12px; }.scenario-stage nav button small { align-self: start; font-size: 9px; }.scenario-stage nav button.active { background: white; color: var(--site-primary-dark); box-shadow: 0 5px 15px rgba(45,62,53,.07); }
.scenario-story { padding: 48px; display: grid; grid-template-columns: 1fr 230px; grid-template-rows: auto 1fr; gap: 34px; background: #f7faf7; }.scenario-story.blue { background: #f2f6f8; }.scenario-story.coral { background: #fbf5f3; }.scenario-story.amber { background: #faf7f0; }.story-copy > span { color: var(--site-primary); font-size: 11px; font-weight: 700; }.blue .story-copy > span { color: var(--site-blue); }.coral .story-copy > span { color: var(--site-coral); }.amber .story-copy > span { color: var(--site-amber); }.story-copy h2 { max-width: 620px; margin-top: 16px; font-size: 40px; line-height: 1.16; }.story-copy p { max-width: 680px; margin-top: 17px; color: var(--site-muted); font-size: 13px; line-height: 1.8; }.story-copy a { margin-top: 24px; display: inline-flex; align-items: center; gap: 8px; color: var(--site-primary-dark); text-decoration: none; font-size: 11px; font-weight: 800; }.story-metrics { display: grid; grid-template-columns: 1fr; border: 1px solid var(--site-line); border-radius: 7px; background: rgba(255,255,255,.72); overflow: hidden; }.story-metrics div { min-height: 72px; padding: 13px; display: flex; flex-direction: column; justify-content: flex-end; border-bottom: 1px solid var(--site-line); }.story-metrics div:last-child { border-bottom: 0; }.story-metrics strong { font-size: 18px; }.story-metrics span { margin-top: 4px; color: var(--site-muted); font-size: 9px; }.story-roles { grid-column: 1 / -1; align-self: end; }.story-roles > span { color: var(--site-muted); font-size: 9px; font-weight: 700; }.story-roles ol { margin-top: 12px; display: grid; grid-template-columns: repeat(4, 1fr); list-style: none; }.story-roles li { position: relative; min-height: 100px; padding: 16px; display: flex; flex-direction: column; border: 1px solid var(--site-line); border-right: 0; background: white; }.story-roles li:last-child { border-right: 1px solid var(--site-line); }.story-roles li b { color: #9aa49e; font-size: 8px; }.story-roles li i { width: 8px; height: 8px; margin-top: 14px; border-radius: 50%; background: var(--site-primary); }.story-roles li strong { margin-top: auto; font-size: 10px; }.story-roles li .el-icon { position: absolute; z-index: 1; right: -10px; top: 40px; width: 20px; height: 20px; display: grid; place-items: center; border-radius: 50%; background: var(--site-primary-dark); color: white; }
.scene-principles { padding: 96px max(30px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: 1.2fr repeat(3, .7fr); background: #e9f0f4; }.principle-intro { padding-right: 50px; }.principle-intro h2 { margin-top: 18px; font-size: 38px; line-height: 1.18; }.scene-principles article { min-height: 260px; padding: 24px; border-left: 1px solid #c7d5dd; }.scene-principles article .el-icon { color: var(--site-blue); font-size: 24px; }.scene-principles article h3 { margin-top: 82px; font-size: 16px; }.scene-principles article p { margin-top: 10px; color: #667985; font-size: 11px; line-height: 1.65; }
.template-wall { padding: 100px max(30px, calc((100vw - 1240px) / 2)); display: grid; grid-template-columns: .7fr 1.3fr; gap: 80px; background: white; }.template-title h2 { margin-top: 18px; font-size: 38px; line-height: 1.18; }.template-title p { margin-top: 16px; color: var(--site-muted); font-size: 13px; line-height: 1.7; }.template-list { border-top: 1px solid var(--site-line); }.template-list article { min-height: 145px; padding: 22px 0; display: grid; grid-template-columns: 80px 1fr; border-bottom: 1px solid var(--site-line); }.template-list article > span { color: var(--site-coral); font-size: 10px; font-weight: 700; }.template-list h3 { font-size: 18px; }.template-list p { grid-column: 2; margin-top: 8px; color: var(--site-muted); font-size: 11px; line-height: 1.6; }
@media (max-width: 980px) { .scenario-intro, .template-wall { grid-template-columns: 1fr; gap: 28px; }.scenario-story { grid-template-columns: 1fr; }.story-metrics { grid-template-columns: repeat(3, 1fr); }.story-metrics div { border-right: 1px solid var(--site-line); border-bottom: 0; }.scene-principles { grid-template-columns: 1fr 1fr 1fr; }.principle-intro { grid-column: 1 / -1; margin-bottom: 30px; } }
@media (max-width: 720px) { .scenario-intro { width: calc(100% - 32px); padding: 60px 0 40px; }.scenario-intro h1 { font-size: 39px; }.scenario-stage { width: calc(100% - 32px); grid-template-columns: 1fr; }.scenario-stage nav { display: grid; grid-template-columns: 1fr 1fr; border-right: 0; border-bottom: 1px solid var(--site-line); }.scenario-stage nav button { min-height: 80px; grid-template-columns: 22px 1fr; }.scenario-stage nav button .el-icon { display: none; }.scenario-story { padding: 28px 16px; }.story-copy h2 { font-size: 30px; }.story-roles ol { grid-template-columns: 1fr 1fr; }.story-roles li { border-right: 1px solid var(--site-line); border-bottom: 0; }.story-roles li .el-icon { display: none; }.scene-principles, .template-wall { padding: 72px 16px; }.scene-principles { grid-template-columns: 1fr; }.principle-intro { grid-column: 1; }.scene-principles article { min-height: 180px; }.scene-principles article h3 { margin-top: 45px; } }
</style>
