apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agenthub
resources:
  - namespace.yaml
  - configmap.yaml
  - java.yaml
  - python.yaml
  - web.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: agenthub
    includeSelectors: true
