# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_hub_pb2 as agent__hub__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AgentExecutionStub(object):
    """==================== Agent 执行服务 ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamExecute = channel.stream_stream(
                '/agenthub.AgentExecution/StreamExecute',
                request_serializer=agent__hub__pb2.ExecutionRequest.SerializeToString,
                response_deserializer=agent__hub__pb2.ExecutionResponse.FromString,
                _registered_method=True)
        self.StopSession = channel.unary_unary(
                '/agenthub.AgentExecution/StopSession',
                request_serializer=agent__hub__pb2.StopSessionRequest.SerializeToString,
                response_deserializer=agent__hub__pb2.StopSessionResponse.FromString,
                _registered_method=True)


class AgentExecutionServicer(object):
    """==================== Agent 执行服务 ====================

    """

    def StreamExecute(self, request_iterator, context):
        """双向流：Java 发送用户消息，Python 流式返回执行结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSession(self, request, context):
        """单向调用：Java 通知 Python 停止某个会话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamExecute': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExecute,
                    request_deserializer=agent__hub__pb2.ExecutionRequest.FromString,
                    response_serializer=agent__hub__pb2.ExecutionResponse.SerializeToString,
            ),
            'StopSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSession,
                    request_deserializer=agent__hub__pb2.StopSessionRequest.FromString,
                    response_serializer=agent__hub__pb2.StopSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenthub.AgentExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenthub.AgentExecution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentExecution(object):
    """==================== Agent 执行服务 ====================

    """

    @staticmethod
    def StreamExecute(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agenthub.AgentExecution/StreamExecute',
            agent__hub__pb2.ExecutionRequest.SerializeToString,
            agent__hub__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenthub.AgentExecution/StopSession',
            agent__hub__pb2.StopSessionRequest.SerializeToString,
            agent__hub__pb2.StopSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolRegistryStub(object):
    """==================== 工具管理服务 ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncTool = channel.unary_unary(
                '/agenthub.ToolRegistry/SyncTool',
                request_serializer=agent__hub__pb2.ToolDef.SerializeToString,
                response_deserializer=agent__hub__pb2.SyncResult.FromString,
                _registered_method=True)
        self.SyncTools = channel.stream_unary(
                '/agenthub.ToolRegistry/SyncTools',
                request_serializer=agent__hub__pb2.ToolDef.SerializeToString,
                response_deserializer=agent__hub__pb2.SyncResult.FromString,
                _registered_method=True)
        self.CheckToolHealth = channel.unary_unary(
                '/agenthub.ToolRegistry/CheckToolHealth',
                request_serializer=agent__hub__pb2.ToolHealthRequest.SerializeToString,
                response_deserializer=agent__hub__pb2.ToolHealthResponse.FromString,
                _registered_method=True)


class ToolRegistryServicer(object):
    """==================== 工具管理服务 ====================

    """

    def SyncTool(self, request, context):
        """Python → Java: 注册/更新工具定义
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncTools(self, request_iterator, context):
        """Python → Java: 批量同步工具列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckToolHealth(self, request, context):
        """Java → Python: 检查工具是否可用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncTool': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncTool,
                    request_deserializer=agent__hub__pb2.ToolDef.FromString,
                    response_serializer=agent__hub__pb2.SyncResult.SerializeToString,
            ),
            'SyncTools': grpc.stream_unary_rpc_method_handler(
                    servicer.SyncTools,
                    request_deserializer=agent__hub__pb2.ToolDef.FromString,
                    response_serializer=agent__hub__pb2.SyncResult.SerializeToString,
            ),
            'CheckToolHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckToolHealth,
                    request_deserializer=agent__hub__pb2.ToolHealthRequest.FromString,
                    response_serializer=agent__hub__pb2.ToolHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenthub.ToolRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenthub.ToolRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolRegistry(object):
    """==================== 工具管理服务 ====================

    """

    @staticmethod
    def SyncTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenthub.ToolRegistry/SyncTool',
            agent__hub__pb2.ToolDef.SerializeToString,
            agent__hub__pb2.SyncResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncTools(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/agenthub.ToolRegistry/SyncTools',
            agent__hub__pb2.ToolDef.SerializeToString,
            agent__hub__pb2.SyncResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckToolHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenthub.ToolRegistry/CheckToolHealth',
            agent__hub__pb2.ToolHealthRequest.SerializeToString,
            agent__hub__pb2.ToolHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ApprovalCallbackStub(object):
    """==================== 审批回调服务 ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnApprovalResult = channel.unary_unary(
                '/agenthub.ApprovalCallback/OnApprovalResult',
                request_serializer=agent__hub__pb2.ApprovalResult.SerializeToString,
                response_deserializer=agent__hub__pb2.Empty.FromString,
                _registered_method=True)


class ApprovalCallbackServicer(object):
    """==================== 审批回调服务 ====================

    """

    def OnApprovalResult(self, request, context):
        """Java → Python: 审批结果通知
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApprovalCallbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnApprovalResult': grpc.unary_unary_rpc_method_handler(
                    servicer.OnApprovalResult,
                    request_deserializer=agent__hub__pb2.ApprovalResult.FromString,
                    response_serializer=agent__hub__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenthub.ApprovalCallback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenthub.ApprovalCallback', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApprovalCallback(object):
    """==================== 审批回调服务 ====================

    """

    @staticmethod
    def OnApprovalResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenthub.ApprovalCallback/OnApprovalResult',
            agent__hub__pb2.ApprovalResult.SerializeToString,
            agent__hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthCheckStub(object):
    """==================== 健康检查服务 ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/agenthub.HealthCheck/Ping',
                request_serializer=agent__hub__pb2.PingRequest.SerializeToString,
                response_deserializer=agent__hub__pb2.PingResponse.FromString,
                _registered_method=True)


class HealthCheckServicer(object):
    """==================== 健康检查服务 ====================

    """

    def Ping(self, request, context):
        """双向健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent__hub__pb2.PingRequest.FromString,
                    response_serializer=agent__hub__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenthub.HealthCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenthub.HealthCheck', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthCheck(object):
    """==================== 健康检查服务 ====================

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenthub.HealthCheck/Ping',
            agent__hub__pb2.PingRequest.SerializeToString,
            agent__hub__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
